name: airlens-airflow

services:
  airflow:
    build: .
    command: standalone
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - ../.env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../resources:/opt/airflow/resources
      - ../serving:/opt/airflow/serving
      - airflow_data:/opt/airflow

volumes:
  airflow_data:
